### ISSUE TITLE
Event on finished

### ISSUE THREAD

**Issue by beckmx** [gillesdemey/node-record-lpcm16#10]
Hello, is there anyway I can recognize when the recording finished?, I see the verbose but I would like to fire an event

**Comment by gillesdemey** [comment]
You might be able to use something like https://github.com/mafintosh/end-of-stream to execute code after the stream ends.

The library will automatically try to detect silence and end the stream.

**Comment by beckmx** [comment]
nice, that fits perfectly with this module, thanx
