### ISSUE TITLE
Recording.

### ISSUE THREAD

**Issue by staminna** [gillesdemey/node-record-lpcm16#12]
I am trying to analyse speech with the module using pipes but sometimes it crashes like this

```
Recording 7146 bytes
End Recording: 2268.685ms
Recording 7146 bytes

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at PassThrough.Writable.write (_stream_writable.js:217:5)
    at Socket.<anonymous> (/Applications/MAMP/htdocs/project/node_modules/node-record-lpcm16/index.js:58:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)

```

All I have is the require and 

```
      // Start recording
        var readableMicrophoneStream = record.start({
          sampleRate : 16000,
          verbose : true
        });
      // Stream the microphone audio to the API
        readableMicrophoneStream
          .pipe(toRecognizeRequest)
          .pipe(call);
```

Any idea? Thanks

**Comment by phanikumar1210** [comment]
I am also having the same issue with this application.  I am trying to run it on windows platform and I have installed sox software as well. an anyone suggest me something on this.

**Comment by sce9sc** [comment]
I also had the same issue . which sow version did you install ?? googling a bit I found that sox-14.3.0 is working

**Comment by gillesdemey** [comment]
Looking at the verbose output it seems like the process is still trying to write to the passthrough stream after the stream has ended.

`v0.1.8` removes the passthrough stream altogether and should fix this issue.
