### ISSUE TITLE
crashing after a while

### ISSUE THREAD

**Issue by sce9sc** [gillesdemey/node-record-lpcm16#15]
Change execa to spawn

**Comment by gillesdemey** [comment]
Cross referencing https://github.com/evancohen/sonus/issues/22

**Comment by evancohen** [comment]
Continuing the discussion from d655da9.

If it actually solves Windows issues then it sounds like `cross-spawn` would be the way to go 👍 

Somewhat related question: Why do you need a PassThrough stream? It doesn't seem necessary. On super low-powered devices (Pi, CHIP, etc) it's additional overhead.

**Comment by gillesdemey** [comment]
Upon investigating it seems that `cross-spawn` isn't really solving any problems that are applicable to us.

**Comment by gillesdemey** [comment]
> Somewhat related question: Why do you need a PassThrough stream? It doesn't seem necessary. On super low-powered devices (Pi, CHIP, etc) it's additional overhead.

I'll see if I can do something about that in the next release, will probably publish it as a minor version bump

**Comment by gillesdemey** [comment]
Published as `0.1.7`

**Comment by evancohen** [comment]
Excellent! Thanks for the quick turn-around :)
