### ISSUE TITLE
Need a way to detect errors from child process

### ISSUE THREAD

**Issue by peller** [gillesdemey/node-record-lpcm16#19]
Such as exposing the result of `spawn` or otherwise emitting error events

**Comment by gillesdemey** [comment]
A proposal in order not to break the current API:

When we receive data on stderr we could simply emit an error on the stdout stream.
```javascript
cp.stderr.on('data', function (data) {
   rec.emit('error', data.toString())
})
```

and then simply attach the error listener before we pipe to our readable stream

```javascript
record.start({
  sampleRate: 44100,
  verbose: true
})
.on('error', err => {
  console.error('stderr said:', err)
})
.pipe(file)
```

This should also seamlessly work with other Stream modules like `through2`, `pumpify`, etc.

Thoughts?

**Comment by mreinstein** [comment]
> When we receive data on stderr we could simply emit an error on the stdout stream.

Seems like a reasonable proposal. 👍

**Comment by sdetweil** [comment]
this doesn't work.. I am seeing the child terminate without notification and I have added all these handlers to the index,js

sometime in the last 30 minutes the arecord process has ended.. 

pi@raspberrypi:~ $ ps -ef | grep arecord
pi         398 25247  2 Dec26 pts/0    00:26:02 arecord -D default -q -r 16000 -c 1 -t wav -f S16_LE -
pi        6548 19336  0 08:34 pts/1    00:00:00 grep --color=auto arecord
pi@raspberrypi:~ $ ps -ef | grep arecord
pi        6726 19336  0 09:03 pts/1    00:00:00 grep --color=auto arecord

I added handlers which recorded the following on a stop() request earlier

12/26/2017 5:38:04 PM lpcm ended=undefined
12/26/2017 5:38:04 PM lpcm error=arecord: pcm_read:2031: read error: Interrupted system call

12/26/2017 5:38:04 PM lpcm closed=child process exited with code 1
12/26/2017 5:38:04 PM lpcm closed=false

		cp.stderr.on('data', function (data) {
  	 rec.emit('error', data.toString())
		})
  cp.stderr.on('error', function(data) {
		rec.emit('close', `child process exited with code ${data}`)
	});
	cp.on('close', function(code) {
		rec.emit('close', `child process exited with code ${code}`)
	});
  cp.on('error', function(data) {
		rec.emit('close', `child process exited with code ${data}`)
	});

and in the using app (sonus)

	sonus.mic.on('error', function(data){
			writelog("lpcm error="+data);
		// rec.emit('error', data.toString())
	})
	sonus.mic.on('end', function(data){
			writelog("lpcm ended="+data);
		// rec.emit('error', data.toString())
	})
	sonus.mic.on('close', function(data){
			writelog("lpcm closed="+data);
		// rec.emit('error', data.toString())
	})
