### ISSUE TITLE
Sox must be started with -d parameter to start continuous recording on Windows

### ISSUE THREAD

**Issue by j-era** [gillesdemey/node-record-lpcm16#21]
see: https://github.com/artcom/node-record-lpcm16/commit/74649305e4a774865d59df48068286844e352641

**Comment by gillesdemey** [comment]
Seems to cause a `rec WARN coreaudio: coreaudio: unhandled buffer overrun.  Data discarded.` exception on MacOS. 

Can you elaborate on why this particular flag is mandatory for Windows?

**Comment by sngc1** [comment]
The same issues on Windows 10 with sox-14.4.1, tested using https://github.com/googleapis/nodejs-speech/tree/master/samples
(replaced `recordProgram` from `rec` to `sox`)

Without `-d` (Use the default audio device)  in  `cmdArgs `, it immediately stops sending audio stream.

**Comment by AxelDolislager** [comment]
> The same issue on Windows 10 with sox-14.4.1, tested using https://github.com/googleapis/nodejs-speech/tree/master/samples
> (replaced `recordProgram` from `rec` to `sox`)
> 
> Without `-d` (Use the default audio device) in `cmdArgs `, it immediately stops sending audio stream.

Hey, I'm having the same issue on my Mac with that module, can you please tell me how you fixed that? I tried removing '-d' from the arguments, but that failed horribly.
Thanks!
