### ISSUE TITLE
2 concurrent recorders on RaspberryPi?

### ISSUE THREAD

**Issue by Vikaton** [gillesdemey/node-record-lpcm16#33]
I have this code that I want to execute:

```js
let fs = require('fs')
let record = require('node-record-lpcm16');
let {Detector, Models} = require('snowboy');

let models = new Models();

models.add({file: 'resources/francisco.pmdl', sensitivity: '0.5', hotwords : 'francisco'});

const detector = new Detector({
  resource: "resources/common.res",
  models: models,
  audioGain: 2.0
});

detector.on('hotword', function (index, hotword) {
  if(hotword === 'francisco') {
    let file = fs.createWriteStream('command.wav', { encoding: 'binary' })
    record.start({
      sampleRateHertz: 16000,
      threshold: 1,
      silence: '1.0',
      verbose: true
    }).pipe(file);
  }
});

record.start({
  sampleRateHertz: 16000,
  threshold: 0,
}).pipe(detector);

console.log('Listening...');
```
The recorder thats piped `detector` works, but when the hot word is detected and the 2nd recorder is initiated, the 2nd recording stops recording immediately (meaning no audio was even recorded). Now there was this one time I was running this script and instead of exiting I stopped it (so it was running in the background) and I went to use `rec temp.wav` and I got an error saying that the device was busy, yet this script works perfectly fine on my OSX as I was able to initiate both recorders.

So is this an issue with the library, RaspberryPi (3), or my microphone USB?

**Comment by mreinstein** [comment]
Unfortunately, this isn't going to work because `node-record-lpcm16` is essentially a singleton internally.

**Comment by Vikaton** [comment]
Is there a reason why `node-record-lpcm16` works with 2 concurrent recordings on OSX if its singleton by design?

**Comment by mreinstein** [comment]
This logic right now seems to be attempting to save audio to a file when a hotword is detected. The problem is multiple hotwords are going to attempt overwrite the `command.wav` file each time.

I guess I'm not sure what you're trying to accomplish with your code.  It might make sense to back up and explain your high level goal.

**Comment by Vikaton** [comment]
It's like Amazon Alexa, You'd say a hot word like 'Alexa' then the script records audio and whatever you say after the hotword is recored to command.wav, then that audio file is your command

I.E:

'Alexa, Whats the Weather?' Then 'Whats the Weather' would be saved in command.wav and the outer recording would continue to hear for more 'Alexa's to record more commands

**Comment by mreinstein** [comment]
@Vikaton this is pseudo code, but I think it will give you the type of structure you're looking for. there's an idle mode, which listens for hotword, and a record mode, which streams wav audio to a file. It ping pongs back and forth between these 2 modes:

```javascript
const fs = require('fs')
// TODO: snowboy setup here


function idleMode() {
  console.log('listening for hotword')
  let detector = snowboy()

  detector.on('hotword', function(index, hotword) {
    record.stop()
    console.log('detected hotword, recording audio')
    recordingMode()
  }))

  record.start().pipe(detector)
}


function recordingMode() {
  const out = fs.createWriteStream('out.wav')
  
  record
    .start()
    .on('close', function() {
      console.log('finished recording audio')
      idleMode()
    })
    .pipe(out)
}

idleMode()
```

**Comment by Vikaton** [comment]
I think I tried this earlier with my rPi but didnt wait for the recording to stop so it exited the application, thanks! Will try again but with better device handling

**Comment by Vikaton** [comment]
Issue was that I needed the declaration of `detector` in `idle()` Thank you!

**Comment by mreinstein** [comment]
glad it worked! :)

**Comment by stursby** [comment]
@Vikaton Would you mind posting you working code? I'm trying to achieve something very similar (on Mac right now, but eventually Pi or something close) and the process is exiting after ~5 seconds or so.

**Comment by Vikaton** [comment]
I just tired your exact code and its not exiting, maybe an issue with the recording program itself?
