### ISSUE TITLE
Unable to record more than 6 seconds 

### ISSUE THREAD

**Issue by danishnazir** [gillesdemey/node-record-lpcm16#34]
Hi there are my options
record.start({
  sampleRate: 16000,
    compress: false,
    threshold: 0.5,
    thresholdStart: null,
    thresholdEnd: null,
    silence: '1.0',
    verbose: true,
    recordProgram: 'sox'
})
I am unable to record more 6 seconds Thanks here is my output through verbose
Recording with sample rate 16000...            
 Recording 5548 bytes                         
  End Recording: 56.070ms

**Comment by ARTI7** [comment]
hi,are you able to resolve this problem?
