### ISSUE TITLE
How can I pause and resume the stream?

### ISSUE THREAD

**Issue by 16alexanders** [gillesdemey/node-record-lpcm16#37]
I'm looking for functionality to pause and resume the stream. I'm using node-record-lpcm16 with Sonus and Snowboy. The problem is that the provided pause() and resume() are not working with node-record-lpcm16.

https://github.com/evancohen/sonus/issues/48#issuecomment-306634719

I tried to use https://www.npmjs.com/package/mic but ran into issues...

**Comment by evancohen** [comment]
Closing because this is a duplicate issue. Please see the other thread.
