### ISSUE TITLE
recorders module loading issue

### ISSUE THREAD

**Issue by laljikanjareeya** [gillesdemey/node-record-lpcm16#52]
getting below error even I have installed sox:

`Error: No such recorder found: sox`

recorder module path is getting wrong on below line:

https://github.com/gillesdemey/node-record-lpcm16/blob/9f27f0985e3c4c045c382f3697b49211e4403dad/recorders/index.js#L5

fix:
```javascript
const recoderPath = path.resolve(__dirname, recorderName) 
```

**Comment by gillesdemey** [comment]
Thanks for reporting! Fixed in https://github.com/gillesdemey/node-record-lpcm16/commit/69be9ba2245eda74fbfa742e882921a0dc8e51f3 and released as [v1.0.1](https://github.com/gillesdemey/node-record-lpcm16/releases/tag/v1.0.1)
